apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: {{ .Values.services.order.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.services.order.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: order-config
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: ORDER_DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservices-secret
                  key: ORDER_DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
