apiVersion: v1
kind: Secret
metadata:
  name: microservices-secret
type: Opaque
stringData:
  PRODUCT_DB_USERNAME: "productuser"
  PRODUCT_DB_PASSWORD: "productpassword"

  ORDER_DB_USERNAME: "orderuser"
  ORDER_DB_PASSWORD: "orderpassword"

  USER_DB_USERNAME: "useruser"
  USER_DB_PASSWORD: "userpassword"

  JWT_SECRET: "my-super-secret-jwt-key"
