spring.application.name=order-service
server.port=8082
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
